# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'Nybkox/tmux-kanagawa'
# set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-plugins "time"
set -g @kanagawa-cwd-max-dirs "0"
set -g @kanagawa-spotify-tui-format "%f %s %t - %a"
set -g @kanagawa-show-powerline true
set -g @kanagawa-cpu-display-load true
set -g @kanagawa-ram-usage-label " "
set -g @kanagawa-network-wifi-label " "
set -g @kanagawa-cpu-display-load true
set -g @kanagawa-battery-label "♥ "

# set scrolling
set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

